return {
  'RESOURCE',
  'CLIENT',
  'SERVER',
  'CLIENT_REPLACED',
  'CLIENT_CONNECTION_TIMED_OUT',
  'CLIENT_CONNECTION_TIMED_OUT_WITH_PENDING_COMMANDS',
  'SERVER_SHUTDOWN',
  'STATE_BAG_RATE_LIMIT',
  'NET_EVENT_RATE_LIMIT',
  'LATENT_NET_EVENT_RATE_LIMIT',
  'COMMAND_RATE_LIMIT',
  'ONE_SYNC_TOO_MANY_MISSED_FRAMES'
}